#define DRIVER_DIR_PIN 2
#define DRIVER_STEP_PIN 3
#define DRIVER_ENABLE_PIN 4
#define STEPPER_INTERFACE_TYPE 1

#define HOME_SWITCH_PIN 8

#define MOVEMENT_SPEED 400
#define STEPPER_SEARCH_SPEED MOVEMENT_SPEED
#define STEPS_PER_MM 160L
#define IDLE_POSITION -100L * STEPS_PER_MM

#define VACUUM_RUNTIME_MS 20 * 1000 